extends Testable

class_name Exception

func _init(m, v=null).(true, m, v):
	pass
